// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SWPSolution.Data.Enum;
using System;
using System.Collections.Generic;

namespace SWPSolution.Data.Entities;

public partial class TrackingPreorder
{
    public string TrackingPreorderId { get; set; }

    public string PreorderId { get; set; }

    public string StaffId { get; set; }

    public DateTime? TrackingDate { get; set; }

    public string Note { get; set; }

    public string Image { get; set; }

    public virtual PreOrder Preorder { get; set; }

    public virtual Staff Staff { get; set; }
}