// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWPSolution.Data.Entities;

public partial class Trackingorder
{
    public string TrackingorderId { get; set; }

    public string OrderId { get; set; }

    public string StaffId { get; set; }

    public DateTime? TrackingDate { get; set; }

    public string Note { get; set; }

    public string Image { get; set; }

    public virtual Order Order { get; set; }

    public virtual Staff Staff { get; set; }
}